"""Minimal PPT generator to create slides from agent outputs."""
from pptx import Presentation
from pptx.util import Inches, Pt
from typing import Dict


def _add_title_slide(prs: Presentation, title: str, subtitle: str = ""):
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    if subtitle:
        slide.placeholders[1].text = subtitle


def _add_bullet_slide(prs: Presentation, heading: str, bullets: list):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = heading
    body = slide.shapes.placeholders[1].text_frame
    body.clear()
    for i, b in enumerate(bullets):
        p = body.add_paragraph() if i > 0 else body.paragraphs[0]
        p.text = b
        p.level = 0


def build_ppt(title: str, aggregated: Dict[str, object], out_path: str = "report.pptx") -> str:
    prs = Presentation()
    _add_title_slide(prs, title, "Generated by KapexAI scaffold")

    # SWOT
    swot = aggregated.get("swot") or {}
    if swot:
        bullets = []
        for k in ("strengths", "weaknesses", "opportunities", "threats"):
            vals = swot.get(k) or []
            bullets.append(f"{k.title()}: {', '.join(vals)}")
        _add_bullet_slide(prs, "SWOT Analysis", bullets)

    # Porter
    porter = aggregated.get("porter") or {}
    if porter:
        bullets = [f"{k.replace('_',' ').title()}: {v}" for k, v in porter.items() if k != "topic"]
        _add_bullet_slide(prs, "Porter Five Forces", bullets)

    # Financial
    fin = aggregated.get("financial") or {}
    if fin:
        bullets = [f"{k.replace('_',' ').title()}: {v}" for k, v in fin.items() if k != "topic"]
        _add_bullet_slide(prs, "Financial Summary", bullets)

    prs.save(out_path)
    return out_path
